language: node_js

node_js:
  - lts/*

cache:
  yarn: true
  directories:
    - public
    - .cache
script:
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: public
  github-token: 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
  keep-history: true
  target_branch: gh-pages
  on:
    branch: master

notifications:
  email: false
